/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package evento_mous_cuadros;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;

/**
 *
 * @author juanj
 */
public class EventosMous extends javax.swing.JFrame {

    /**
     * Creates new form EventosMous
     */
    public EventosMous() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Linea = new javax.swing.JRadioButton();
        Cuadrado = new javax.swing.JRadioButton();
        Circulo = new javax.swing.JRadioButton();
        Numero = new javax.swing.JComboBox<>();
        rojo = new javax.swing.JRadioButton();
        verde = new javax.swing.JRadioButton();
        amarillo = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        buttonGroup1.add(Linea);
        Linea.setText("Lineas");
        Linea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LineaActionPerformed(evt);
            }
        });

        buttonGroup1.add(Cuadrado);
        Cuadrado.setText("Cuadrados");
        Cuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuadradoActionPerformed(evt);
            }
        });

        buttonGroup1.add(Circulo);
        Circulo.setText("Circulos");
        Circulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CirculoActionPerformed(evt);
            }
        });

        Numero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tamaño 1", "Tamaño 2", "Tamaño 3", "Tamaño 4", "Normal", " " }));
        Numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumeroActionPerformed(evt);
            }
        });

        buttonGroup2.add(rojo);
        rojo.setText("rojo");

        buttonGroup2.add(verde);
        verde.setText("verde");

        buttonGroup2.add(amarillo);
        amarillo.setText("amarillo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rojo)
                            .addComponent(verde)
                            .addComponent(amarillo))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Cuadrado)
                            .addComponent(Circulo)
                            .addComponent(Linea))))
                .addContainerGap(212, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(Numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Circulo)
                            .addComponent(rojo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Cuadrado)
                            .addComponent(verde))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Linea)
                            .addComponent(amarillo))))
                .addContainerGap(183, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
      
    //Aqui se declaran variables que seran utilizadas para guardar los puntos
    int General =0,click1x,click1y,click2x,click2y;
      
    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
      
        //Importamos la libreria Grapics para poder dibujar
        Graphics g = getGraphics();
        Graphics2D g2d = (Graphics2D)g;
        //Aqui definimos el Grosor de las Figuras
        BasicStroke Grosor1=new BasicStroke(10);
        BasicStroke Grosor2=new BasicStroke(20);
        BasicStroke Grosor3=new BasicStroke(30);
        BasicStroke Grosor4=new BasicStroke(40);
        String opcion = Numero.getSelectedItem().toString();
         
        if (Linea.isSelected()) {
            General ++;
            //si el residuo es cero se ejecutara esto
            if ((General % 2 == 0)) { 
                // Aqui guardamos los puntos de la segunda ves que se le de click 
                click1x=evt.getX();
                click1y=evt.getY();
                
                if (rojo.isSelected()) {
                    if(opcion.equals("Normal")){
                    
                    g.setColor(Color.red);
                    g.drawLine(click1x,click1y,click2x,click2y);
                    
                    }
                    if(opcion.equals("Tamaño 1")){
                    g2d.setStroke(Grosor1);
                    g.setColor(Color.red);
                    g.drawLine(click1x,click1y,click2x,click2y);
                    
                    }
                    if(opcion.equals("Tamaño 2")){
                    g2d.setStroke(Grosor2);
                    g.setColor(Color.red);
                    g.drawLine(click1x,click1y,click2x,click2y);
                    
                    }
                    if(opcion.equals("Tamaño 3")){
                    g2d.setStroke(Grosor3);
                    g.setColor(Color.red);
                    g.drawLine(click1x,click1y,click2x,click2y);
                    
                    }
                    if(opcion.equals("Tamaño 4")){
                    g2d.setStroke(Grosor4);
                    g.setColor(Color.red);
                    g.drawLine(click1x,click1y,click2x,click2y);
                    
                    }

                    
                    
                    
                }else if (verde.isSelected()) {
                    if(opcion.equals("Normal")){
                    
                    g.setColor(Color.green);
                    g.drawLine(click1x,click1y,click2x,click2y);
                    
                    }
                    if(opcion.equals("Tamaño 1")){
                    g2d.setStroke(Grosor1);
                    g.setColor(Color.green);
                    g.drawLine(click1x,click1y,click2x,click2y);
                    
                    }
                     if(opcion.equals("Tamaño 2")){
                    g2d.setStroke(Grosor2);
                    g.setColor(Color.green);
                    g.drawLine(click1x,click1y,click2x,click2y);
                    
                    }
                      if(opcion.equals("Tamaño 3")){
                    g2d.setStroke(Grosor3);
                    g.setColor(Color.green);
                    g.drawLine(click1x,click1y,click2x,click2y);
                    
                    }
                       if(opcion.equals("Tamaño 4")){
                    g2d.setStroke(Grosor4);
                    g.setColor(Color.green);
                    g.drawLine(click1x,click1y,click2x,click2y);
                    
                    }
                }else if (amarillo.isSelected()) {
                    
                    if(opcion.equals("Normal")){
                    
                    g.setColor(Color.yellow);
                    g.drawLine(click1x,click1y,click2x,click2y);
                    
                    }
                    if(opcion.equals("Tamaño 1")){
                    g2d.setStroke(Grosor1);
                    g.setColor(Color.yellow);
                    g.drawLine(click1x,click1y,click2x,click2y);
                    
                    }
                    if(opcion.equals("Tamaño 2")){
                    g2d.setStroke(Grosor2);
                    g.setColor(Color.yellow);
                    g.drawLine(click1x,click1y,click2x,click2y);
                    
                    }if(opcion.equals("Tamaño 3")){
                    g2d.setStroke(Grosor3);
                    g.setColor(Color.yellow);
                    g.drawLine(click1x,click1y,click2x,click2y);
                    
                    }if(opcion.equals("Tamaño 4")){
                    g2d.setStroke(Grosor4);
                    g.setColor(Color.yellow);
                    g.drawLine(click1x,click1y,click2x,click2y);
                    
                    }
                    
                }
                // si no se selecciona ningun color se dibujara una linea negra 
               g.drawLine(click1x,click1y,click2x,click2y);
                
            } else if ((General % 2) !=0) {
                click2x=evt.getX();
                click2y=evt.getY();
            }
        }
        // Este system sirve pra mostrar las coordenadas en consola 
      System.out.println(evt.getX()+" "+evt.getY());
          
      // Si el usuario elije esa opccion se dibujara un cuadrado
      if (Circulo.isSelected()) {
              if (rojo.isSelected()) {
                  // Estas condicionales sirven para elejir el color tamaño y Grosor de las figuras
                  if(opcion.equals("Normal")){
                    
                    g.setColor(Color.red);
                     g.drawOval(evt.getX(), evt.getY(), evt.getX(), evt.getY());
                    
                    }
                    if(opcion.equals("Tamaño 1")){
                    g2d.setStroke(Grosor1);
                    g.setColor(Color.red);
                     g.drawOval(evt.getX(), evt.getY(), evt.getX(), evt.getY());
                    
                    }
                    if(opcion.equals("Tamaño 2")){
                    g2d.setStroke(Grosor2);
                    g.setColor(Color.red);
                     g.drawOval(evt.getX(), evt.getY(), evt.getX(), evt.getY());
                    
                    }
                    if(opcion.equals("Tamaño 3")){
                    g2d.setStroke(Grosor3);
                    g.setColor(Color.red);
                     g.drawOval(evt.getX(), evt.getY(), evt.getX(), evt.getY());
                    
                    }
                    if(opcion.equals("Tamaño 4")){
                    g2d.setStroke(Grosor4);
                    g.setColor(Color.red);
                     g.drawOval(evt.getX(), evt.getY(), evt.getX(), evt.getY());
                    
                    }
                  
              }
              else if (verde.isSelected()) {
                   if(opcion.equals("Normal")){
                    
                     g.setColor(Color.green);
                     g.drawOval(evt.getX(), evt.getY(), evt.getX(), evt.getY());
                    
                    }
                    if(opcion.equals("Tamaño 1")){
                    g2d.setStroke(Grosor1);
                     g.setColor(Color.green);
                     g.drawOval(evt.getX(), evt.getY(), evt.getX(), evt.getY());
                    
                    }
                    if(opcion.equals("Tamaño 2")){
                    g2d.setStroke(Grosor2);
                     g.setColor(Color.green);
                     g.drawOval(evt.getX(), evt.getY(), evt.getX(), evt.getY());
                    
                    }
                    if(opcion.equals("Tamaño 3")){
                    g2d.setStroke(Grosor3);
                    g.setColor(Color.green);
                     g.drawOval(evt.getX(), evt.getY(), evt.getX(), evt.getY());
                    
                    }
                    if(opcion.equals("Tamaño 4")){
                    g2d.setStroke(Grosor4);
                     g.setColor(Color.green);
                     g.drawOval(evt.getX(), evt.getY(), evt.getX(), evt.getY());
                    
                    }
                  
                  
              }else if (amarillo.isSelected()) {
                  if(opcion.equals("Normal")){
                    
                      g.setColor(Color.yellow);
                     g.drawOval(evt.getX(), evt.getY(), evt.getX(), evt.getY());
                    
                    }
                    if(opcion.equals("Tamaño 1")){
                    g2d.setStroke(Grosor1);
                      g.setColor(Color.yellow);
                     g.drawOval(evt.getX(), evt.getY(), evt.getX(), evt.getY());
                    
                    }
                    if(opcion.equals("Tamaño 2")){
                    g2d.setStroke(Grosor2);
                      g.setColor(Color.yellow);
                     g.drawOval(evt.getX(), evt.getY(), evt.getX(), evt.getY());
                    
                    }
                    if(opcion.equals("Tamaño 3")){
                    g2d.setStroke(Grosor3);
                     g.setColor(Color.yellow);
                     g.drawOval(evt.getX(), evt.getY(), evt.getX(), evt.getY());
                    
                    }
                    if(opcion.equals("Tamaño 4")){
                    g2d.setStroke(Grosor4);
                     g.setColor(Color.yellow);
                     g.drawOval(evt.getX(), evt.getY(), evt.getX(), evt.getY());
                    
                    }
                 
                 
              }
              g.drawOval(evt.getX(), evt.getY(), evt.getX(), evt.getY());
              
            
        }
      //estos if sirven para poder dibujar un cuadrado 
          if (Cuadrado.isSelected()) {
              if (rojo.isSelected()) {
                  if(opcion.equals("Normal")){
                    
                      g.setColor(Color.red);
                     g.drawRect(evt.getX(),evt.getY(),evt.getX(), evt.getY());
                    
                    }
                    if(opcion.equals("Tamaño 1")){
                    g2d.setStroke(Grosor1);
                      g.setColor(Color.red);
                  g.drawRect(evt.getX(),evt.getY(),evt.getX(), evt.getY());
                    
                    }
                    if(opcion.equals("Tamaño 2")){
                    g2d.setStroke(Grosor2);
                     g.setColor(Color.red);
                     g.drawRect(evt.getX(),evt.getY(),evt.getX(), evt.getY());
                    
                    }
                    if(opcion.equals("Tamaño 3")){
                    g2d.setStroke(Grosor3);
                     g.setColor(Color.red);
                     g.drawRect(evt.getX(),evt.getY(),evt.getX(), evt.getY());
                    
                    }
                    if(opcion.equals("Tamaño 4")){
                    g2d.setStroke(Grosor4);
                     g.setColor(Color.red);
                     g.drawRect(evt.getX(),evt.getY(),evt.getX(), evt.getY());
                    
                    }
                  
                  
              } else if (verde.isSelected()) {
                  if(opcion.equals("Normal")){
                    
                      g.setColor(Color.green);
                     g.drawRect(evt.getX(),evt.getY(),evt.getX(), evt.getY());
                    
                    }
                    if(opcion.equals("Tamaño 1")){
                    g2d.setStroke(Grosor1);
                     g.setColor(Color.green);
                  g.drawRect(evt.getX(),evt.getY(),evt.getX(), evt.getY());
                    
                    }
                    if(opcion.equals("Tamaño 2")){
                    g2d.setStroke(Grosor2);
                     g.setColor(Color.green);
                     g.drawRect(evt.getX(),evt.getY(),evt.getX(), evt.getY());
                    
                    }
                    if(opcion.equals("Tamaño 3")){
                    g2d.setStroke(Grosor3);
                     g.setColor(Color.green);
                     g.drawRect(evt.getX(),evt.getY(),evt.getX(), evt.getY());
                    
                    }
                    if(opcion.equals("Tamaño 4")){
                    g2d.setStroke(Grosor4);
                     g.setColor(Color.green);
                     g.drawRect(evt.getX(),evt.getY(),evt.getX(), evt.getY());
                    
                    }
                  
                  
              }
              else if (amarillo.isSelected()) {
                  if(opcion.equals("Normal")){
                    
                      g.setColor(Color.yellow);
                     g.drawRect(evt.getX(),evt.getY(),evt.getX(), evt.getY());
                    
                    }
                    if(opcion.equals("Tamaño 1")){
                    g2d.setStroke(Grosor1);
                     g.setColor(Color.yellow);
                     g.drawRect(evt.getX(),evt.getY(),evt.getX(), evt.getY());
                    
                    }
                    if(opcion.equals("Tamaño 2")){
                    g2d.setStroke(Grosor2);
                     g.setColor(Color.yellow);
                     g.drawRect(evt.getX(),evt.getY(),evt.getX(), evt.getY());
                    
                    }
                    if(opcion.equals("Tamaño 3")){
                    g2d.setStroke(Grosor3);
                     g.setColor(Color.yellow);
                     g.drawRect(evt.getX(),evt.getY(),evt.getX(), evt.getY());
                    
                    }
                    if(opcion.equals("Tamaño 4")){
                    g2d.setStroke(Grosor4);
                     g.setColor(Color.yellow);
                     g.drawRect(evt.getX(),evt.getY(),evt.getX(), evt.getY());
                    
                    }
                  
                 
              }
              
            g.drawRect(evt.getX(),evt.getY(),evt.getX(), evt.getY());
        }
          
          
          
          
    }//GEN-LAST:event_jPanel1MouseClicked

    private void LineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LineaActionPerformed
      
    }//GEN-LAST:event_LineaActionPerformed

    private void CuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuadradoActionPerformed
       
    }//GEN-LAST:event_CuadradoActionPerformed

    private void CirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CirculoActionPerformed
        
    }//GEN-LAST:event_CirculoActionPerformed

    private void NumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumeroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EventosMous.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EventosMous.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EventosMous.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EventosMous.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EventosMous().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Circulo;
    private javax.swing.JRadioButton Cuadrado;
    private javax.swing.JRadioButton Linea;
    private javax.swing.JComboBox<String> Numero;
    private javax.swing.JRadioButton amarillo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rojo;
    private javax.swing.JRadioButton verde;
    // End of variables declaration//GEN-END:variables
}
